Title: Linear Algebra (private)
author: me, built with <a href="https://teachbooks.io">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a> #add your own name here

execute:
  execute_notebooks: "off"

only_build_toc_files: false

html:
  baseurl :  "https://douden.github.io/openlabook/" #Replace this with your own URL

sphinx:
  config:
    sphinx_indexed_defs_indexed_nodes: ['strong','emphasis','literal']
    sphinx_indexed_defs_skip_indices: ['\bdet\w*','\$i\$-th entry','\(main\) diagonal']
    sphinx_indexed_defs_lowercase_indices: true
    sphinx_indexed_defs_index_titles: true
    sphinx_indexed_defs_capital_words: ['Dimension']
    ref_graph_remove_links: ['Introduction.html -> Colophon/Acknowledgements.html']
    ref_graph_tag_color: {'Eigenvalues':'#900bee','Matrix operations':'#0cd734'}
    # ref_graph_group_nodes: true
    ref_graph_internal_links: true
    # ref_graph_collapse_group: true
    ref_graph_toc_links: true
    numfig_secnum_depth: 2
    html_static_path:
    - _static
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      logo:
        text: Linear Algebra (private)
      repository_url: "https://github.com/douden/openlabook" #add your own repo URL here
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: true
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
    latex_elements:
          preamble: |
            \usepackage{chemmacros}
            \newcommand{\vect}[1]{\overrightarrow{#1}}
            \newcommand{\N}{\mathbb{N}}
            \newcommand{\R}{\mathbb{R}}
            \newcommand{\C}{\mathbb{C}}
            \newcommand{\ip}{\mathbf{\cdot}}
            \renewcommand{\iff}{\Longleftrightarrow}
            \newcommand{\ce}{\ch}
            \newcommand{\cp}{\times }
            \newcommand{\norm}[1]{\left\Vert{#1}\right\Vert}
            \newcommand{\abs}[1]{\left\vert{#1}\right\vert}
            \renewcommand{\Span}[1]{\operatorname{Span}\left\lbrace#1\right\rbrace}
            \newcommand{\Col}[1]{\ensuremath{{\rm Col\,}{#1}}}
            \newcommand{\Nul}[1]{\ensuremath{{\rm Nul\,}{#1}}}
            \newcommand{\Rank}[1]{\ensuremath{{\rm rank\,}{#1}}}
            \newcommand{\Row}[1]{\ensuremath{{\rm Row\,}{#1}}}
            \newcommand{\Det}[1]{\operatorname{det}\left(#1\right)}
            \renewcommand{\det}[1]{\operatorname{det}\left(#1\right)}
            \renewcommand{\Re}[1]{\operatorname{Re}\left(#1\right)}
            \renewcommand{\Im}[1]{\operatorname{Im}\left(#1\right)}
            \renewcommand{\proj}{\operatorname{proj} }
            \newcommand{\nicefrac}{\frac }
            \newcommand{\mc}{\mathcal}
            \newcommand{\Arg}{\operatorname{Arg}}
            \newcommand{\PB}{P_{\mathcal{B}}}
            \newcommand{\CoBmatrix}[2]{P_{{\mathcal #2}\leftarrow{\mathcal #1}}}
            \usepackage{tabularx}
            \usepackage{threeparttable}
    mathjax3_config: 
      tex:
        inlineMath: [ ['$','$'], ['\(','\)'] ]
        displayMath: [ ['$$','$$'], ['\[','\]'] ]
        macros:
          "CoBmatrix": ["P_{{\\mathcal #2}\\leftarrow{\\mathcal #1}} ",2]
          "mc": "\\mathcal"
          "PB": "P_{\\mathcal B}"
          "N": "\\mathbb{N}"
          "C": "\\mathbb{C}"
          "R": "\\mathbb{R}"
          "ip" : "\\mathbf{\\cdot}"
          "vect": ["\\mathbf{#1}",1]
          "abs": ["\\left\\vert #1 \\right\\vert",1]
          "norm": ["\\left\\Vert #1 \\right\\Vert",1]
          "cp": ["\\times "]
          "Nul": ["{\\rm Nul}\\, #1", 1]
          "Col": ["{\\rm Col}\\, #1", 1]
          "Row": ["{\\rm Row}\\, #1", 1]
          "Rank": ["{\\rm rank}\\, #1", 1]
          "nicefrac": ["\\frac "]
          "proj": ["\\operatorname{proj} "]
          "Span": ["\\operatorname{Span}\\left\\lbrace #1 \\right\\rbrace",1]
          "Det": ["\\operatorname{det}\\left(#1\\right)",1]
          "Re": ["\\operatorname{Re}\\left(#1\\right)",1]
          "Im": ["\\operatorname{Im}\\left(#1\\right)",1]
  extra_extensions:
    - sphinx_proof
    - sphinx_togglebutton
    - sphinx_exercise
    - teachbooks_sphinx_grasple
    - sphinx.ext.imgconverter
    - sphinx_tudelft_theme
    - teachbooks_sphinx_tippy
    - jupyterbook_patches
    - sphinx_prime_applets
    - sphinx_design
    - sphinx_image_inverter
    - sphinx_ref_graph
  local_extensions:
    latextable: _ext/
    latexlist: _ext/
    parentheses_list: _ext/
    def_to_index: _ext/